"""
PageIndex — Stage 4 of the Document Intelligence Refinery

A hierarchical navigation tree over a document — the equivalent of a
"smart table of contents" that an LLM can traverse to locate information
without reading the entire document.

Inspired by VectifyAI's PageIndex concept.
"""
from typing import Optional
from pydantic import BaseModel, Field


# ------------------------------------------------------------
# Named entity found within a section
# ------------------------------------------------------------

class SectionEntity(BaseModel):
    """A key named entity extracted from a section."""
    text: str
    entity_type: str = Field(
        ...,
        description="e.g. 'ORG', 'DATE', 'MONEY', 'PERCENT', 'PERSON'"
    )


# ------------------------------------------------------------
# A single node in the PageIndex tree
# ------------------------------------------------------------

class PageIndexNode(BaseModel):
    """
    A single section node in the document navigation tree.
    Can have child sections forming a hierarchy.

    Example tree:
      Chapter 3: Financial Results  (page 45-60)
        ├── 3.1 Revenue Analysis    (page 45-50)
        │     └── 3.1.1 Q3 Breakdown (page 48-50)
        └── 3.2 Cost Analysis       (page 51-60)
    """
    node_id: str = Field(..., description="Unique ID: {doc_id}_node_{index}")
    doc_id: str

    # Section identity
    title: str = Field(..., description="Section heading text")
    level: int = Field(
        default=1,
        description="Heading depth: 1=chapter, 2=section, 3=subsection"
    )

    # Page span
    page_start: int = Field(..., description="First page of this section (1-indexed)")
    page_end: int = Field(..., description="Last page of this section (1-indexed)")

    # Content summary — generated by a fast LLM
    summary: str = Field(
        default="",
        description="2-3 sentence LLM-generated summary of this section's content"
    )

    # Key entities found in this section
    key_entities: list[SectionEntity] = Field(
        default_factory=list,
        description="Named entities extracted from this section"
    )

    # Data types present in this section
    data_types_present: list[str] = Field(
        default_factory=list,
        description="e.g. ['tables', 'figures', 'equations', 'footnotes']"
    )

    # LDU IDs that belong to this section
    chunk_ids: list[str] = Field(
        default_factory=list,
        description="IDs of all LDUs that fall within this section"
    )

    # Tree structure
    parent_node_id: Optional[str] = Field(
        default=None,
        description="ID of the parent section node (None for root nodes)"
    )
    child_node_ids: list[str] = Field(
        default_factory=list,
        description="IDs of direct child section nodes"
    )


# ------------------------------------------------------------
# PageIndex — the full document navigation tree
# ------------------------------------------------------------

class PageIndex(BaseModel):
    """
    The complete hierarchical navigation structure for one document.
    Stored at: .refinery/pageindex/{doc_id}.json

    Use case: When a user asks 'What are the Q3 capital expenditure projections?'
    the retrieval agent first traverses the PageIndex to find the relevant
    section, then does vector search only within that section's chunks —
    rather than searching the entire document corpus.
    """
    doc_id: str
    filename: str
    total_pages: int

    # All nodes — flat list, tree structure encoded via parent/child IDs
    nodes: list[PageIndexNode] = Field(default_factory=list)

    # Root node IDs (top-level sections with no parent)
    root_node_ids: list[str] = Field(default_factory=list)

    # Document-level summary
    document_summary: str = Field(
        default="",
        description="High-level summary of the entire document"
    )

    # Quick lookup helpers
    total_sections: int = Field(default=0)
    total_chunks_indexed: int = Field(default=0)

    def get_node(self, node_id: str) -> Optional[PageIndexNode]:
        """Retrieve a node by its ID."""
        for node in self.nodes:
            if node.node_id == node_id:
                return node
        return None

    def get_nodes_for_page(self, page_number: int) -> list[PageIndexNode]:
        """Return all nodes whose page span includes the given page."""
        return [
            node for node in self.nodes
            if node.page_start <= page_number <= node.page_end
        ]

    def search_by_title(self, query: str) -> list[PageIndexNode]:
        """Simple title keyword search — used before vector search."""
        query_lower = query.lower()
        return [
            node for node in self.nodes
            if query_lower in node.title.lower()
            or query_lower in node.summary.lower()
        ]
